package com.example.demo.model;

import java.io.Serializable;
import java.util.Date;

public class TbHistory201611 implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.Msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.SrcId
     *
     * @mbggenerated
     */
    private Integer srcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.SpNumber
     *
     * @mbggenerated
     */
    private String spnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.MsgId
     *
     * @mbggenerated
     */
    private String msgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.sid
     *
     * @mbggenerated
     */
    private Long sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.SendFlag
     *
     * @mbggenerated
     */
    private Boolean sendflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.ErrorCode
     *
     * @mbggenerated
     */
    private String errorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.PkTotal
     *
     * @mbggenerated
     */
    private Integer pktotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.MNumber
     *
     * @mbggenerated
     */
    private Integer mnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.PkNumber
     *
     * @mbggenerated
     */
    private Integer pknumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.RptTime
     *
     * @mbggenerated
     */
    private Date rpttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.SubTime
     *
     * @mbggenerated
     */
    private Date subtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.Readflag
     *
     * @mbggenerated
     */
    private Integer readflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_history_2016_11.TotalCount
     *
     * @mbggenerated
     */
    private Integer totalcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_history_2016_11
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.uid
     *
     * @return the value of tb_history_2016_11.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.uid
     *
     * @param uid the value for tb_history_2016_11.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.id
     *
     * @return the value of tb_history_2016_11.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.id
     *
     * @param id the value for tb_history_2016_11.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.phone
     *
     * @return the value of tb_history_2016_11.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.phone
     *
     * @param phone the value for tb_history_2016_11.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.Msg
     *
     * @return the value of tb_history_2016_11.Msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.Msg
     *
     * @param msg the value for tb_history_2016_11.Msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.SrcId
     *
     * @return the value of tb_history_2016_11.SrcId
     *
     * @mbggenerated
     */
    public Integer getSrcid() {
        return srcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.SrcId
     *
     * @param srcid the value for tb_history_2016_11.SrcId
     *
     * @mbggenerated
     */
    public void setSrcid(Integer srcid) {
        this.srcid = srcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.SpNumber
     *
     * @return the value of tb_history_2016_11.SpNumber
     *
     * @mbggenerated
     */
    public String getSpnumber() {
        return spnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.SpNumber
     *
     * @param spnumber the value for tb_history_2016_11.SpNumber
     *
     * @mbggenerated
     */
    public void setSpnumber(String spnumber) {
        this.spnumber = spnumber == null ? null : spnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.MsgId
     *
     * @return the value of tb_history_2016_11.MsgId
     *
     * @mbggenerated
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.MsgId
     *
     * @param msgid the value for tb_history_2016_11.MsgId
     *
     * @mbggenerated
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid == null ? null : msgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.sid
     *
     * @return the value of tb_history_2016_11.sid
     *
     * @mbggenerated
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.sid
     *
     * @param sid the value for tb_history_2016_11.sid
     *
     * @mbggenerated
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.SendFlag
     *
     * @return the value of tb_history_2016_11.SendFlag
     *
     * @mbggenerated
     */
    public Boolean getSendflag() {
        return sendflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.SendFlag
     *
     * @param sendflag the value for tb_history_2016_11.SendFlag
     *
     * @mbggenerated
     */
    public void setSendflag(Boolean sendflag) {
        this.sendflag = sendflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.ErrorCode
     *
     * @return the value of tb_history_2016_11.ErrorCode
     *
     * @mbggenerated
     */
    public String getErrorcode() {
        return errorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.ErrorCode
     *
     * @param errorcode the value for tb_history_2016_11.ErrorCode
     *
     * @mbggenerated
     */
    public void setErrorcode(String errorcode) {
        this.errorcode = errorcode == null ? null : errorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.PkTotal
     *
     * @return the value of tb_history_2016_11.PkTotal
     *
     * @mbggenerated
     */
    public Integer getPktotal() {
        return pktotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.PkTotal
     *
     * @param pktotal the value for tb_history_2016_11.PkTotal
     *
     * @mbggenerated
     */
    public void setPktotal(Integer pktotal) {
        this.pktotal = pktotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.MNumber
     *
     * @return the value of tb_history_2016_11.MNumber
     *
     * @mbggenerated
     */
    public Integer getMnumber() {
        return mnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.MNumber
     *
     * @param mnumber the value for tb_history_2016_11.MNumber
     *
     * @mbggenerated
     */
    public void setMnumber(Integer mnumber) {
        this.mnumber = mnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.PkNumber
     *
     * @return the value of tb_history_2016_11.PkNumber
     *
     * @mbggenerated
     */
    public Integer getPknumber() {
        return pknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.PkNumber
     *
     * @param pknumber the value for tb_history_2016_11.PkNumber
     *
     * @mbggenerated
     */
    public void setPknumber(Integer pknumber) {
        this.pknumber = pknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.RptTime
     *
     * @return the value of tb_history_2016_11.RptTime
     *
     * @mbggenerated
     */
    public Date getRpttime() {
        return rpttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.RptTime
     *
     * @param rpttime the value for tb_history_2016_11.RptTime
     *
     * @mbggenerated
     */
    public void setRpttime(Date rpttime) {
        this.rpttime = rpttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.SubTime
     *
     * @return the value of tb_history_2016_11.SubTime
     *
     * @mbggenerated
     */
    public Date getSubtime() {
        return subtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.SubTime
     *
     * @param subtime the value for tb_history_2016_11.SubTime
     *
     * @mbggenerated
     */
    public void setSubtime(Date subtime) {
        this.subtime = subtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.Readflag
     *
     * @return the value of tb_history_2016_11.Readflag
     *
     * @mbggenerated
     */
    public Integer getReadflag() {
        return readflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.Readflag
     *
     * @param readflag the value for tb_history_2016_11.Readflag
     *
     * @mbggenerated
     */
    public void setReadflag(Integer readflag) {
        this.readflag = readflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_history_2016_11.TotalCount
     *
     * @return the value of tb_history_2016_11.TotalCount
     *
     * @mbggenerated
     */
    public Integer getTotalcount() {
        return totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_history_2016_11.TotalCount
     *
     * @param totalcount the value for tb_history_2016_11.TotalCount
     *
     * @mbggenerated
     */
    public void setTotalcount(Integer totalcount) {
        this.totalcount = totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history_2016_11
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", id=").append(id);
        sb.append(", phone=").append(phone);
        sb.append(", msg=").append(msg);
        sb.append(", srcid=").append(srcid);
        sb.append(", spnumber=").append(spnumber);
        sb.append(", msgid=").append(msgid);
        sb.append(", sid=").append(sid);
        sb.append(", sendflag=").append(sendflag);
        sb.append(", errorcode=").append(errorcode);
        sb.append(", pktotal=").append(pktotal);
        sb.append(", mnumber=").append(mnumber);
        sb.append(", pknumber=").append(pknumber);
        sb.append(", rpttime=").append(rpttime);
        sb.append(", subtime=").append(subtime);
        sb.append(", readflag=").append(readflag);
        sb.append(", totalcount=").append(totalcount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}