package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import com.example.demo.model.TbHistory201611;

@Mapper
@Repository
public interface TbHistory201611Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history_2016_11
     *
     * @mbggenerated
     */
    int insert(TbHistory201611 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history_2016_11
     *
     * @mbggenerated
     */
    List<TbHistory201611> selectAll();
    
    TbHistory201611 getOne(Long id);
}